# Generated by Django 2.2.17 on 2021-03-30 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Artist', models.CharField(max_length=30)),
                ('Cover', models.ImageField(blank=True, upload_to='Album_Cover')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Picture', models.ImageField(blank=True, upload_to='Profile_pic')),
                ('Location', models.CharField(max_length=30)),
                ('Date_Joined', models.DateField()),
                ('Number_Of_Reviews', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Of_Review', models.DateField()),
                ('Rating', models.FloatField(default=0)),
                ('Written_Review', models.TextField(max_length=1000)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxapp.Album')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(max_length=1000)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxapp.Album')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicboxapp.User')),
            ],
        ),
    ]
