# Generated by Django 2.2.17 on 2021-04-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicboxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Date_Of_Review',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicboxapp.Review'),
        ),
        migrations.AddField(
            model_name='album',
            name='Genre',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='Release',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='Date_Of_Review',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date_Joined',
            field=models.DateField(default=None, null=True),
        ),
    ]
