# Generated by Django 2.2.17 on 2021-04-04 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicboxapp', '0002_auto_20210401_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name_plural': 'Albums'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Written_Review',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Date_Joined',
            new_name='Joined',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Number_Of_Reviews',
            new_name='Total_Reviews',
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='Date_Posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Interest',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Occupation',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Comment',
            field=models.TextField(),
        ),
    ]
