# Generated by Django 2.2.17 on 2021-04-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicboxapp', '0004_auto_20210409_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
